### ISSUE TITLE
jackson jar包版本不对

### ISSUE THREAD

**Issue by wolfduan** [dogmanss/quant4j#9]
<jackson.version>2.9.10.1</jackson.version>这个版本仓库没有，是打错了么

**Comment by dogmanss** [comment]
上maven仓库里找找其他版本替换一下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: wolfduan <notifications@github.com&gt;
发送时间: 2020年2月7日 13:40
收件人: dogmanss/quant4j <quant4j@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[dogmanss/quant4j] jackson jar包版本不对 (#9)




<jackson.version&gt;2.9.10.1</jackson.version&gt;这个版本仓库没有，是打错了么

**Comment by wolfduan** [comment]
已经处理，只是提下有这个坑，后来同学可以直接用2.9.10版本。
